# Generated by Django 2.0 on 2019-03-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNum1',
            new_name='ReadNum',
        ),
    ]
